### PR TITLE
Add --space-before-function-paren option

### PR DESCRIPTION
**Pull request by josephfrazier**
This corresponds to ESLint's `space-before-function-paren` "always"
option: http://eslint.org/docs/rules/space-before-function-paren#always

See https://github.com/prettier/prettier/issues/1139

Note that this is based on upstream prettier's master branch, so that should be merged before this. Only the last two commits in this PR are the meaningful ones.

### CODE REVIEW

**Comment by rhengles** [comment]
Thank you! I just updated the master branch, but there have been some changes.

Can you solve the conflicts please?

**Comment by josephfrazier** [comment]
Sure thing, I also added documentation.

**Comment by sabrehagen** [comment]
@josephfrazier Can you submit this as a merge request to the [`prettier/prettier`](https://github.com/prettier/prettier) repository? This fork is getting very out of date, and this functionality would be very useful in the main prettier library.

**Comment by josephfrazier** [comment]
At https://github.com/prettier/prettier/, this has been split into https://github.com/prettier/prettier/issues/3845 and https://github.com/prettier/prettier/issues/3847 (this one has a PR at https://github.com/prettier/prettier/pull/3903)

**Comment by suconghou** [comment]
why this function  `--space-before-function-paren` still not online in 2.2.1

**Pull request merged**
